development:
  host: '127.0.0.1'
  port: 9042
  keyspace: paris_rb_cassandra_development

test:
  host: '127.0.0.1'
  port: 9042
  keyspace: paris_rb_cassandra_test

production:
  hosts:
    - 'cass1.paris_rb_cassandra.biz'
    - 'cass2.paris_rb_cassandra.biz'
    - 'cass3.paris_rb_cassandra.biz'
  port: 9042
  keyspace: paris_rb_cassandra_production
  username: 'myappuser'
  password: 'password1'
